Traceback (most recent call last):
  File "xbrl2rdf/xbrl2rdf.py", line 46, in <module>
    main()
  File "xbrl2rdf/xbrl2rdf.py", line 42, in main
    command_builder.execute(args)
  File "/home/barry/code/rdfconverters/rdfconverters/util.py", line 80, in execute
    self.commands[args.command](args)
  File "/home/barry/code/rdfconverters/rdfconverters/util.py", line 116, in command
    raise IOError("Output directory does not exist or is not a directory: %s" % args.output)
IOError: Output directory does not exist or is not a directory: /home/barry/data/xebrberdf
